### ISSUE TITLE
React 18 compatibility

### ISSUE THREAD

**Issue by thomassb** [stripe/react-stripe-js#273]
### Summary
React 18 was made available on March 29, 2022.
Current depedencies
`"react": "^16.8.0 || ^17.0.0",`

Has anyone conducted a compatibility upgrade test?

**Comment by christopher-stripe** [comment]
Hi @thomassb, I ran a quick test and found that changes in React 18 break React Stripe.js completely when using a hybrid server/client setup.

So, we don't currently support React 18, but plan to. I'll update here once we have a more concrete timeline

**Comment by RhRU** [comment]
> Hi @thomassb, I ran a quick test and found that changes in React 18 break React Stripe.js completely when using a hybrid server/client setup.
> 
> So, we don't currently support React 18, but plan to. I'll update here once we have a more concrete timeline

Hy Christopher. Do you have any updates on this issue?

**Comment by Theofilos-Chamalis** [comment]
I can confirm I have the same issue with Next.js v12.1.4 and react/react-dom v.18.0.0

**Comment by caprica** [comment]
Related I suppose, following the React example from https://stripe.com/docs/payments/quickstart with React 18 in strict mode causes warnings to be emitted like "Unsupported prop change: options.clientSecret is not a mutable property.", because of the double-invocation of the useEffect. I don't know if that is a benign warning or not yet.

**Comment by navdesign** [comment]
I ran into the same issue when I upgraded my next js app from 11 to 12. I have react-dom version - 18. Right now I can't make any stripe element to work. The element does not show up in the iframe. 

The problem is with the "loadStripe" instance. According to stripe docs if you pass a Promise to the [Elements provider](https://stripe.com/docs/stripe-js/react#elements-provider) and the Promise has not yet resolved, then useElements will return null.

If anyone has a solution then let me know... Thanks :)

**Comment by vbudovski** [comment]
How about something like this? https://codesandbox.io/s/awesome-hooks-qmkoqh?file=/src/App.js

**Comment by tettoffensive** [comment]
I'm thinking this is why I'm getting typescript errors with React 18 and Stripe Elements:

```ts
const stripePromise = loadStripe(process.env.STRIPE_PUBLISHABLE_KEY ?? '');

const StripeCheckout = ({ user }: { user: User }) => {
  return (
    <Elements stripe={stripePromise}>
      <CheckoutForm user={user} />
    </Elements>
  );
};
```

```ts
Type error: Type '{ children: Element; stripe: Promise<Stripe | null>; }' is not assignable to type 'IntrinsicAttributes & ElementsProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & ElementsProps'.
```

**Comment by blvdmitry** [comment]
@tettoffensive Yes, that's exactly that. A lot of packages got to this migration path as they have to add children manually to their typings. Same applies here.

**Comment by bmathews-stripe** [comment]
The typescript issue has been resolved in @stripe/react-stripe-js v1.7.2. 

We're working on a fix for React 18's StrictMode and will update this thread once resolved.

**Comment by tomaszzmudzinski** [comment]
Stripe is the last npm library which is not prepared for react 18 in our project 🙈 Do you even know the date when you will be ready for it?

**Comment by akibrahimug** [comment]
Is there an alternative approach to the issue with the stripe Elements.

**Comment by dwetoskey** [comment]
I'm currently in the same boat and wondering if there is a different payment processor package that will work with React 18, but so far I'm striking out.

**Comment by nirmalshah88** [comment]
Any updates on when we can expect this to roll out?

**Comment by BhaskaranR** [comment]
> Any updates on when we can expect this to roll out?

+1

**Comment by dwetoskey** [comment]
Just so everyone is aware that might be finishing up a project like myself, the PayPal packages do seem to be working with React 18. Hopefully the Stripe packages will be ready soon.

**Comment by thefrisson** [comment]
Would also like to know when the update for React 18 will be released... Just getting into real React to use libraries like Stripe (I usually use Plotly Dash for frontend development), and thought I had somehow incorrectly created my project components, only to find out that it is a compatibility issue with Stripe on one of the most widely used web frameworks....

**Comment by dangolbeeker** [comment]
I'm working on a pull request  react-hooks-testing-library needs updating as well...

**Comment by tomaszzmudzinski** [comment]
> I'm working on a pull request it should be ready by the end of the week.
> 
> * I do not work for Stripe

Sick situation, but everyone will be grateful ❤️

**Comment by tylersmith-stripe** [comment]
**Update:** We have a PR under review for React 18 support: https://github.com/stripe/react-stripe-js/pull/292. (thank you @bmathews-stripe & @christopher-stripe!)

**Comment by bmathews-stripe** [comment]
We've published a pre-release version with these changes: `"@stripe/react-stripe-js": "1.8.0-0"`. 

Let us know if you run into any issues with this!

**Comment by bmathews-stripe** [comment]
Promoted these changes to v1.8.0.

`"@stripe/react-stripe-js": "1.8.0"`

`yarn add @stripe/react-stripe-js@1.8.0`
